# Run all Plant keeper services
# - Plant-keeper django REST Api Gateway
# - Plant-keeper Prometheus client server
# - Plant-keeper device controller
# - Postgres database
# - Prometheus server
# - Grafana server
#
# Author : Vigneswaran Shanmugathas
# mail : shamugathas.vigneswaran@outlook.fr

version: "3.7"

services:

  loki:
    image: grafana/loki:master-89263b0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    network_mode: host
    image: grafana/promtail:latest
    volumes:
      - ${PWD}/confs/promtail-docker-config.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    ports:
      - "9080:9080"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  plant-keeper-api-gateway:
    build:
      context: .
    command: bash -c "bash init.sh && gunicorn --workers=3 --bind 0.0.0.0:8001 plant_kiper.wsgi"
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - db

  plant-keeper-device-ctl:
    build:
      context: .
    command: bash -c "cd controllers && python run.py"
    restart: always
    depends_on:
      - db
      - plant-keeper-api-gateway

  grafana:
    image: grafana/grafana:6.7.1
    restart: always
    ports:
     - 3000:3000
