version: "3.7"

services:
  plant-keeper:
    image: plant-keeper:1
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
  prom:
    image: prom/prometheus:latest
    restart: always
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
     - 9090:9090
    depends_on:
      - plant-keeper
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
     - 3000:3000
    depends_on:
      - prom