{
 "title": "Dev",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  air_co2_ppm AS \"time\",\n  air_temperature\nFROM plant_core_plantsettings\nORDER BY 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  air_co2_ppm AS \"time\",\n  air_hygrometry\nFROM plant_core_plantsettings\nORDER BY 1"
    }
   ]
  },
  {
   "title": "My Plant",
   "type": "graph",
   "gridPos": { "h": 24, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  enclosure_temperature AS \"Temperature\"\nFROM plant_core_enclosure\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  enclosure_hygrometry AS \"Humidity\"\nFROM plant_core_enclosure\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  air_co2_ppm AS \"time\",\n  soil_hygrometry\nFROM plant_core_plantsettings\nORDER BY 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 2 },
   "format": "ppm",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  air_co2_ppm AS \"time\",\n  air_co2_ppm\nFROM plant_core_plantsettings\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Controllers Status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  power_status AS \"humidifier\"\nFROM plant_core_airhumidifier\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  power_status AS \"cooler\"\nFROM plant_core_cooler\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  power_status AS \"heater\"\nFROM plant_core_heater\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  power_status AS \"CO2\"\nFROM plant_core_co2valve\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Controllers Log",
   "type": "logs",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{logger=\"controllers-logger\"}"
    }
   ]
  }
 ]
}