{
 "title": "Cooler",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  humidity_in\nFROM plant_core_cooler\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  humidity_level_max\nFROM plant_core_cooler\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  humidity_level_min\nFROM plant_core_cooler\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  temperature_in\nFROM plant_core_cooler\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  temperature_level_max\nFROM plant_core_cooler\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  temperature_level_min\nFROM plant_core_cooler\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cooler Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{controller=\"cooler\"}"
    }
   ]
  },
  {
   "title": "Humidity Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  power_humidity\nFROM plant_core_cooler\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperature Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  power_temperature\nFROM plant_core_cooler\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  }
 ]
}